### ISSUE TITLE
not able to pass build

### ISSUE THREAD

**Issue by hero-intelligent** [daeuniverse/daed-revived-next#21]
9644207b0380e7771d602c13895e64760479154b was the last version that can pass build.

clone then checkout

**Comment by kunish** [comment]
let me see, did you build using bun or nodejs?

**Comment by kunish** [comment]
<img width="636" alt="image" src="https://github.com/daeuniverse/daed-revived-next/assets/17328586/6e6bf3b7-394e-4ae6-b703-bd80a14887e0">

works fine for me

**Comment by kunish** [comment]
oh, by the way, are there any error messages?

**Comment by kunish** [comment]
Maybe it's an issue related to bun?
